import {
  BRANCHES_ENDPOINT,
  DEPARTMENTS_ENDPOINT,
  DIVISIONS_ENDPOINT,
  BASE_URL as ENV_BASE_URL,
  LOGIN_ENDPOINT,
  PRESENCE_ENDPOINT,
  PRESENCE_IN_ENDPOINT,
  PRESENCE_OUT_ENDPOINT,
  REGISTER_ENDPOINT,
  USER_ENDPOINT,
} from '@env';

export const BASE_URL = ENV_BASE_URL;

export const API_ENDPOINTS = {
  LOGIN: LOGIN_ENDPOINT,
  REGISTER: REGISTER_ENDPOINT,
  DIVISIONS: DIVISIONS_ENDPOINT,
  DEPARTMENTS: DEPARTMENTS_ENDPOINT,
  BRANCHES: BRANCHES_ENDPOINT,
  USER: USER_ENDPOINT,
  PRESENCE_IN: PRESENCE_IN_ENDPOINT,
  PRESENCE_OUT: PRESENCE_OUT_ENDPOINT,
  PRESENCE: PRESENCE_ENDPOINT,
};
