export const ROUTE = {
  mainNavigator: 'MainNavigator',
  authNavigator: 'AuthNavigator',
  authScreen: 'AuthScreen',
  homeStack: 'HomeStack',
  scanStack: 'ScanStack',
  settingStack: 'SettingStack',
  loginScreen: 'Login',
  registerScreen: 'Register',
  settingScreen: 'Setting',
  homeScreen: 'Home',
  scanScreen: 'Scan',
  dynamicModal: 'DynamicModalWrapper',
  codeScanner: 'CodeScanner',
};
